### ISSUE TITLE
Protein Search taking over 20 seconds

### ISSUE THREAD

**Issue by kaimikacolin** [oceanproteinportal/api#11]
This query is taking over 20 seconds to return. Is there any way to optimize this?

```
SELECT DISTINCT ?protein ?product_name ?dataset ?dataset_name ?expedition ?spectral_count ?protein_id ?peptide_count ?sequence ?ids
        WHERE { 
        ?protein a <http://schema.oceanproteinportal.org/v2/views/ProteinFound> .
        ?protein ?p ?o .
        FILTER REGEX(?o, "AA", "i")
        
        ?protein view:productName ?product_name .
        ?protein view:identifiers ?ids .
        ?protein view:datasetName ?dataset_name .
        ?protein view:dataset ?dataset .
        ?protein view:expedition ?expedition .
        ?protein view:spectralCount ?spectral_count .
        ?protein view:proteinID ?protein_id .
        ?protein view:peptideCount ?peptide_count .
        ?protein view:sequence ?sequence .
        }
        ORDER BY DESC(?spectral_count)

```

**Comment by jaclynsaunders** [comment]
@kaimikacolin - It's the FILTER REGEX line. I'll look into whether there's a way to expedite this. Virtuoso is slower than some other engines with regex. tbd

**Comment by ashepherd** [comment]
specifying the properties you want to search over will speed it up:

```
SELECT DISTINCT ?protein ?product_name ?dataset ?dataset_name ?expedition ?spectral_count ?protein_id ?peptide_count ?sequence ?ids
        WHERE { 
        VALUES ?p { view:productName view:identifiers view:expedition view:proteinID view:sequence }
        ?protein a <http://schema.oceanproteinportal.org/v2/views/ProteinFound> .
        ?protein ?p ?o .
        FILTER REGEX(?o, "AA", "i")
        
        ?protein view:productName ?product_name .
        ?protein view:identifiers ?ids .
        ?protein view:datasetName ?dataset_name .
        ?protein view:dataset ?dataset .
        ?protein view:expedition ?expedition .
        ?protein view:spectralCount ?spectral_count .
        ?protein view:proteinID ?protein_id .
        ?protein view:peptideCount ?peptide_count .
        ?protein view:sequence ?sequence .
        }
        ORDER BY DESC(?spectral_count)
```

`view:sequence` in the filter will be expensive

**Comment by jaclynsaunders** [comment]
@kaimikacolin - is this still a lingering issue?

**Comment by kaimikacolin** [comment]
This trimmed the time down to about 15 seconds, that's great. Let me know if you have any other optimizations!

@ashepherd @jaclynsaunders

**Comment by jaclynsaunders** [comment]
Low priority -- continued optimization perhaps, but working at an ok level. Maybe try to speed up search when have bandwidth

**Comment by jaclynsaunders** [comment]
@kaimikacolin - [I restructured this string query search](https://kg.oceanproteinportal.org/?query=SELECT+DISTINCT+%3Fprotein+%3Fproduct_name+%3Fdataset+%3Fdataset_name+%3Fexpedition+%3Fspectral_count+%3Fprotein_id+%3Fpeptide_count+%3Fsequence+%3Fids%0D%0A++++++++WHERE+%7B+%0D%0A++++++++VALUES+%3Fp+%7B+view%3AproductName+view%3Aidentifiers+view%3Aexpedition+view%3AproteinID+view%3Asequence+%7D%0D%0A++++++++%3Fprotein+a+%3Chttp%3A%2F%2Fschema.oceanproteinportal.org%2Fv2%2Fviews%2FProteinFound%3E+.%0D%0A++++++++%7B%0D%0A++++++++%7B+%3Fprotein+view%3AproductName+%3Fproduct_name+.%0D%0A+++++++++FILTER+REGEX%28%3Fproduct_name%2C+%22AA%22%2C+%22i%22%29+%7D%0D%0A++++++++UNION%0D%0A++++++++%7B+%3Fprotein+view%3Aidentifiers+%3Fids+.+%0D%0A+++++++++FILTER+REGEX%28%3Fids%2C+%22AA%22%2C+%22i%22%29+%7D%0D%0A++++++++%7D%0D%0A++++++++%3Fprotein+view%3AdatasetName+%3Fdataset_name+.%0D%0A++++++++%3Fprotein+view%3Adataset+%3Fdataset+.%0D%0A++++++++%3Fprotein+view%3Aexpedition+%3Fexpedition+.%0D%0A++++++++%3Fprotein+view%3AspectralCount+%3Fspectral_count+.%0D%0A++++++++%3Fprotein+view%3AproteinID+%3Fprotein_id+.%0D%0A++++++++%3Fprotein+view%3ApeptideCount+%3Fpeptide_count+.%0D%0A++++++++%3Fprotein+view%3Asequence+%3Fsequence+.%0D%0A++++++++%7D%0D%0A++++++++ORDER+BY+DESC%28%3Fspectral_count%29). Instead of searching through every single field, it will now only search a regex on the protein product name as well as any of the additional ids (NCBI taxon, pfam, uniprot, etc.). It searches all of the ids, so both the id name as well as the descriptions. Will just need to change the hard coded string "AA" to some input variable. 

```
SELECT DISTINCT ?protein ?product_name ?dataset ?dataset_name ?expedition ?spectral_count ?protein_id ?peptide_count ?sequence ?ids
        WHERE { 
        VALUES ?p { view:productName view:identifiers view:expedition view:proteinID view:sequence }
        ?protein a <http://schema.oceanproteinportal.org/v2/views/ProteinFound> .
        {
        { ?protein view:productName ?product_name .
         FILTER REGEX(?product_name, "AA", "i") }
        UNION
        { ?protein view:identifiers ?ids . 
         FILTER REGEX(?ids, "AA", "i") }
        }
        ?protein view:datasetName ?dataset_name .
        ?protein view:dataset ?dataset .
        ?protein view:expedition ?expedition .
        ?protein view:spectralCount ?spectral_count .
        ?protein view:proteinID ?protein_id .
        ?protein view:peptideCount ?peptide_count .
        ?protein view:sequence ?sequence .
        }
        ORDER BY DESC(?spectral_count)
```

**Comment by jaclynsaunders** [comment]
@ashepherd sped up these queries significantly, so I'm closing this issue
